print("--- 19)-Desarrollar un algoritmo que permita ir de la casa al trabajo.---")
input()
print("Inicio")
input()
print("\t1-Salir de la casa.")
input()
print("\t2-Tomar un medio de transporte,")
input()
print("\t3-Dirigirse al trabajo.")
input()
print("Fin")
input()
