print("--- 13)-Desarrollar un algoritmo que permita apagar un bombillo. ---")
input()
print("Inicio.")
input()
print("\t1-Dirigirse hacia el bombillo.")
input()
print("\t2-Verificar si esta encendido.")
input()
print("\t3-Dirigirse al interruptor.")
input()
print("\t4-Apagar el bombillo.")
input()
print("Fin.")
input()
