print("--- 39)-Desarrollar un algoritmo que permita se duerma.")
input()
print("Inicio")
input()
print("\t1-Doblamos la esquina superior dependiendo")
input()
print("\t2-Colocamos al bebé encima de la manta con su cuelllo.")
input()
print("\t3-Cogemos la esquina izquierda del arrullo y la doblamos ")
input()
print("\t4-Cogemos la esquina inferior del arrullo manteniendo su brazo izquierdo en una buena posición.")
input()
print("\t5-Con lo que nos queda cogeremos desde el pecho")
input()
print("\t6-Con el resto del arrullo intentamos quitar el máximo de arrugas ")
input()
print("\t7-Con lo que nos sobra deberemos pasarlo por debajo del bebé ")
input()
print("Fin")
input()
