print("1)-Desarrollar un algoritmo que permita adquirir una revista.")
input()
print("Inicio.")
input()
print("\t2-Identificar el tipo de revista que necesitamos")
input()
print("\t3-Ir a una tienda.")
input()
print("\t4-Preguntar si tienen la revista.")
input()
print("\t5-Si la tienen comprarla")
input()
print("\t6-Si no la tienen repetir el paso 2")
input()
print("Fin")
