print("--- 45)-Desarrollar un algoritmo que permita descifrar un jeroglífico..")
input()
print("Inicio")
input()
print("\t1-Ver un geroglfico.")
input()
print("\t2-Si sabemos el lenguaje jeroglifico")
input()
print("\t\t3-Leer para descifralo\t")
input()
print("\t4-sino")
input()
print("\t\t5-buscar un diccionario.")
input()
print("\t\t6-descifrarlo.")
input()
print("Fin")
input()

