print("--- 11)-Desarrollar un algoritmo que permita tocar determinada canción con un instrumento musical. ---")
input()
print("Inicio")
input()
print("\t1-Saber que instrumento deseamos tocar.")
input()
print("\t2-Buscar el intrumento.")
input()
print("\t3-Sujetar el  instrumento.")
input()
print("\t4.Tocar dicho instrumento")
input()
print("Fin")
input()
