print("--- 31-)Desarrollar un algoritmo que permita manejar un monociclo.")
input()
print("Inicio")
input()
print("\t1-Coloca tu mano en una baranda para mantener el equilibrio mientras colocas tu pie en el pedal más alto.")
input()
print("\t2-Mantén tu otro pie en el suelo mientras te subes a la silla.")
input()
print("\t3-eleva tu pie del lado interior y colócalo sobre el pedal interior.")
input()
print("\t4- de montar el monociclo sin sostenerte de nada.")
input()
print("\t 5-Pisa el pedal derecho, coloca tu pie izquierdo en el pedal izquierdo y siéntate en la silla mientras se esté levantando.")
input()
print("Fin")
input()
