print("--- 43)- Desarrollar un algoritmo que permita tirarse desde un avión con un paracaídas.")
input()
print("Inicio")
input()
print("\t1-Llama a la zona de salto, pregunta sus horarios y  programa un salto en paracaídas.")
input()
print("\t2-Resuelve todas tus dudas antes de que pagues por el  salto.")
input()
print("\t3-Escoge el método para tu primer salto Caída Libre Acelerada.")
input()
print("\t4-vístete de acuerdo al clima en la tierra y usa tenis.")
input()
print("\t5-Aborda el avión.")
input()
print("\t6-Sal del avión con todo el equipaje para saltar.")
input()
print("\t7-¡Disfrútalo!. ")
input()
print("Fin")
input()

