print("--- 27)Desarrollar un algoritmo que permita cortarse el cabello.")
input()
print("Inicio")
input()
print("\t1-Saber que corte deseamos.")
input()
print("\t2-Si estamos en dentro de un lugar.")
input()
print("\t\t3-salir de ese lugar.")
input()
print("\t4-Fin si")
input()
print("\t5-Dirigirnos hacia la barbería más cercana.")
input()
print("\t6-Entrar al local.")
input()
print("\t7-Verificar si hay turno.")
input()
print("\t8-Si hay turno.")
input()
print("\t\t9-sentarse.")
input()
print("\t\t10-Pedir el corte deseado.")
input()
print("\t11-Sino")
input()
print("\t\t12-Esperar el turno.")
input()
print("\tSi ya hay turno.")
input()
print("\t\t14-Sentarse.")
input()
print("\t15-Pedir el corte deseadoprint.")
input()
print("\t16-Fin si.")
input()
print("Fin")
input()
