print("--- 21)-Desarrollar un algoritmo que permita quitarse una camisa.---")
input()
print("Inicio")
input()
print("\t1-Verificar si tenemos una camisa puesta")
input()
print("\t2-si la tenemos")
input()
print("\t\t3-si es de botones")
input()
print("\t\t4-desabotonar uno a uno los botones")
input()
print("\t5-sino")
input()
print("\t\t6-descabrocharla")
print("Fin")
input()
