print("3--Desarrollar un algoritmo que permita dar un beso")
input()
print("Inicio.")
input()      
print("\t1-Localizar a la persona, objeto o cosa a la que se le  dará el beso.")
input()
print("\t2-Acercarse a la persona, objeto o cosa.")
input()
print("\t3-Dar beso.")
input()
print("Fin")
