print("--- 49)-Desarrollar un algoritmo que permita elevar una cometa.")
input()
print("Inicio")
input()
print("\t1-asegurarnos de tener la cometa e hilo")
input()
print("\t2-Dirigirnos a un lugar con mucho viento.")
input()
print("\t3-Tomar la cometa.")
input()
print("\t4-Colocarnos de espalda al viento")
input()
print("\t5-Correr en direccion contraria al viento")
input()
print("\t6-Se elevo la cometa.")
input()
print("\t7.si se elevo la cometa\n\t\t disfruta.")
input()
print("\t8.si no \n\t\t repetir el paso desde el paso 2")
print("Fin")
input()

