print("--- 33)-Desarrollar un algoritmo que permita hacer un pastel.")
input()
print("Inicio")
input()
print("\t1-Conseguir los ingredientes necesarios para la   creación del pastel.(huevo, harina, claras ,cuchara, vainilla, almíbar). ")
input()
print("\t2-Batir la clara.")
input()
print("\t3-disolver azúcar.")
input()
print("\t4-Agregar harina.")
input()
print("\t5-Elegir un molde.")
input()
print("\t6-Echar mantequilla.")
input()
print("\t7-Llevar al horno por 45 minutos.")
input()
print("\t8-Retiralo de horno")
input()
print("\t9-Dejar que se enfrie.")
input()
print("\t10-Ponerle almibar.")
input()
print("11-Añadir alguna fruta de su gusto.")
input()
print("Fin")
input()
