print("5---Desarrollar un algoritmo que permita encender un vehículo---")
input()
print("Inicio.")
input()
print("\t1-Ir a vehículo.")
input()
print("\t2-Subir al vehículo.")
input()
print("\t3-Verificar que tenemos la llave")
input()
print("\t4-Colocar la llave.")
input()
print("\t5-Encender el vehículo.")
input()
print("Fin.")
input()
