print("--- 35)-Desarrollar un algoritmo que permita adquirir un pantalón.")
input()
print("Inicio")
input()
print("\t1-Dirigirse a una tienda.")
input()
print("\t2-Preguntar si tienen pantalón.")
input()
print("\t3-Si lo tienen adquirirlo.")
input()
print("\t4-Si no lo tienen volver al paso 1.")
input()
print("Fin")
input()
