print("---9)-Desarrollar un algoritmo que permita tomar un baño.---")
input()
print("Inicio.")
input()
print("\t1-Ir hacia el baño.")
input()
print("\t2-Quitarse la ropa.")
input()
print("\t3-Entrar en la bañera.")
input()
print("\t4-Abrir el grifo.")
input()
print("\t5-Tomar el baño.")
input()
print("Fin.")
input()
