print("--- 15)-Desarrollar un algoritmo que permita apagar una vela. ---")
input()
print("Inicio")
input()
print("\t1-Buscar la vela.")
input()
print("\t2-Verificar que este encendida.")
input()
print("\t4-Acercarse ala vela.")
input()
print("\t5-Soplar hacia la llama.")
input()
print("\t6-Hasta a pagar la vela.")
input()
print("Fin")
input()
