print("--- 23)-Desarrollar un algoritmo que permita abrir una ventana.---")
input()
print("Inicio")
input()
print("\t1-Identificar la ventana que vamos abrir")
input()
print("\t2-Dirigirnos hacia la ventana.")
input()
print("\t3-Cerrar la ventana.")
input()
print("Fin")
input()
