print("--- 17)-Desarrollar un algoritmo que permita almorzar.---")
input()
print("Inicio")
input()
print("\t1-Tener claro lo que deseamos almorzar.")
input()
print("\t2-Buscar el lugar en donde decíamos almorzar.")
input()
print("\t3-Preparar almuerzo.")
input()
print("\t4-Comer almuerzo.")
input()
print("Fin")
input()
