print("--- 29)-Desarrollar un algoritmo que permita manejar una bicicleta.")
input()
print("Inicio")
input()
print("\t1-Ponernos un casco y rodilleras.")
input()
print("\t2-Si no disponemos de una bicicleta.")
input()
print("\t\t3-Conseguir una prestada.")
input()
print("\t4-Sacarla hacia un lugar muy espacioso.")
input()
print("\t5-Parar la biccleta.")
input()
print("\t6-Montarnos en el sillin.")
input()
print("\t7-Colocar el los pies en los pedales.")
input()
print("Fin")
input()
