print("--- 41)- Desarrollar un algoritmo que permita jugar ping-pong.")
input()
print("Inicio")
input()
print("\t1-Dirigirnos a un lugar donde halla una mesa de ping pong.")
input()
print("\t2-Tomar una paleta.")
input()
print("\t3-Buscar un oponente.")
input()
print("\t3-Buscar un oponente.")
input()
print("Fin")
input()
