print("--- 25)- Desarrollar un algoritmo que permita tomar una fotografía.")
input()
print("Inicio")
input()
print("\t1-Conseguir una camara.")
input()
print("\t2-Dirigirse a un lugar donde decíamos tomar la fotografía.")
input()
print("\t3-Tomar la fotografía.")
input()
print("Fin")
input()
