print("--- 35)-Desarrollar un algoritmo que permita adquirir un pantalón.")
input()
print("Inicio")
input()
print("\t1-Tener un periódico.")
input()
print("\t2-Abrir el periódico. ")
input()
print("\t   3-Leer el periódico.")
input()
print("Fin")
input()
