print("--- 47-Desarrollar un algoritmo que permita quitarse los zapatos.")
input()
print("Inicio")
input()
print("\t1-Asegurarse de tener zapatos")
input()
print("\t2-Si ¿tenemos zapatos? Entonces")
input()
print("\t\t3-Desbrochar las agujetas")
input()
print("\t\t4-Proceder a retirar el zapato derecho")
input()
print("\t\t5-Retirar el zapato izquierdo")
input()
print(" 6-Fin Si")
print("Fin")
input()

