print("--- 7)-Desarrollar un algoritmo que permita mirar por un telescopio ---")
input()
print("Inicio")
input()
print("\t1-Ir hacia un observatorio.")
input()
print("\t2-Preguntar si tienen un telescopio.")
input()
print("\t3-Ir hacia el telescopio.")
input()
print("\t4-Mirar por el telescopio.")
input()
print("\t5-En caso de no tener un telescopio repetir el paso 1.")
input()
print("Fin.")
